//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationManagementProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigurationItem()
        {
            this.DependencyItems = new HashSet<DependencyItem>();
            this.DependencyItems1 = new HashSet<DependencyItem>();
        }
    
        public int ID { get; set; }
        public string CIName { get; set; }
        public string CIDescripton { get; set; }
        public string CIVersion { get; set; }
        public string States { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DependencyItem> DependencyItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DependencyItem> DependencyItems1 { get; set; }
    }
}
