//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationManagementProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DependencyItem
    {
        public int ID { get; set; }
        public int IDBaseCI { get; set; }
        public int IDDependencyCI { get; set; }
        public string States { get; set; }
    
        public virtual ConfigurationItem ConfigurationItem { get; set; }
        public virtual ConfigurationItem ConfigurationItem1 { get; set; }
    }
}
